=== const39/lore-tracker/src/schemas/save_format_v3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SaveFormat",
  "definitions": {
    "SaveFormat": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "days": {
          "type": "number"
        },
        "season": {
          "$ref": "#/definitions/Season"
        },
        "cards": {
          "$ref": "#/definitions/CardsStoreSerialized"
        },
        "quickNote": {
          "type": "string"
        },
        "_meta": {
          "$ref": "#/definitions/MetaData"
        }
      },
      "required": [
        "_meta",
        "cards",
        "days",
        "name",
        "quickNote",
        "season"
      ],
      "additionalProperties": false
    },
    "Season": {
      "type": "string",
      "enum": [
        "spring",
        "summer",
        "autumn",
        "winter"
      ]
    },
    "CardsStoreSerialized": {
      "type": "object",
      "properties": {
        "quest": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22quest%22%3E%3E"
        },
        "event": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22event%22%3E%3E"
        },
        "location": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22location%22%3E%3E"
        },
        "character": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22character%22%3E%3E"
        },
        "faction": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22faction%22%3E%3E"
        },
        "note": {
          "$ref": "#/definitions/SerializedFolder%3CCardFolderMetadata%2CCardTypeBasedOnCategory%3C%22note%22%3E%3E"
        }
      },
      "required": [
        "quest",
        "event",
        "location",
        "character",
        "faction",
        "note"
      ],
      "additionalProperties": false
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"quest\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22quest%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardFolderMetadata": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/ID"
        },
        "name": {
          "type": "string"
        },
        "color": {
          "type": "string"
        },
        "_category": {
          "$ref": "#/definitions/CardCategory"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        }
      },
      "required": [
        "_category",
        "color",
        "id",
        "name",
        "tags"
      ],
      "additionalProperties": false
    },
    "ID": {
      "type": "number"
    },
    "CardCategory": {
      "type": "string",
      "enum": [
        "quest",
        "event",
        "location",
        "character",
        "faction",
        "note"
      ]
    },
    "CardTypeBasedOnCategory<\"quest\">": {
      "$ref": "#/definitions/Quest",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Quest": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "quest"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "title": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "tasks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Task"
          }
        }
      },
      "required": [
        "_category",
        "desc",
        "id",
        "tags",
        "tasks",
        "title"
      ],
      "additionalProperties": false
    },
    "Task": {
      "type": "object",
      "properties": {
        "isCompleted": {
          "type": "boolean"
        },
        "desc": {
          "type": "string"
        }
      },
      "required": [
        "isCompleted",
        "desc"
      ],
      "additionalProperties": false
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"event\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22event%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardTypeBasedOnCategory<\"event\">": {
      "$ref": "#/definitions/Event",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Event": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "event"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "desc": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/EventType"
        },
        "day": {
          "type": "number"
        }
      },
      "required": [
        "_category",
        "day",
        "desc",
        "id",
        "tags",
        "type"
      ],
      "additionalProperties": false
    },
    "EventType": {
      "type": "string",
      "enum": [
        "combat",
        "encounter",
        "discovery",
        "travel",
        "other"
      ]
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"location\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22location%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardTypeBasedOnCategory<\"location\">": {
      "$ref": "#/definitions/Location",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Location": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "location"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        }
      },
      "required": [
        "_category",
        "desc",
        "id",
        "name",
        "tags"
      ],
      "additionalProperties": false
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"character\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22character%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardTypeBasedOnCategory<\"character\">": {
      "$ref": "#/definitions/Character",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Character": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "character"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "name": {
          "type": "string"
        },
        "race": {
          "type": "string"
        },
        "classes": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "isNPC": {
          "type": "boolean"
        },
        "isAlive": {
          "type": "boolean"
        },
        "desc": {
          "type": "string"
        }
      },
      "required": [
        "_category",
        "classes",
        "desc",
        "id",
        "isAlive",
        "isNPC",
        "name",
        "race",
        "role",
        "tags"
      ],
      "additionalProperties": false
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"faction\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22faction%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardTypeBasedOnCategory<\"faction\">": {
      "$ref": "#/definitions/Faction",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Faction": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "faction"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "name": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        }
      },
      "required": [
        "_category",
        "desc",
        "id",
        "name",
        "tags"
      ],
      "additionalProperties": false
    },
    "SerializedFolder<CardFolderMetadata,CardTypeBasedOnCategory<\"note\">>": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "metadata": {
            "$ref": "#/definitions/CardFolderMetadata"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CardTypeBasedOnCategory%3C%22note%22%3E"
            }
          },
          "parent": {
            "type": "string",
            "description": "Data type of the keys used to index a FlatFolder."
          },
          "subfolders": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Data type of the keys used to index a FlatFolder."
            }
          }
        },
        "required": [
          "files",
          "metadata",
          "subfolders"
        ],
        "additionalProperties": false,
        "description": "Structure of a flattened Folder object."
      },
      "propertyNames": {
        "description": "Data type of the keys used to index a FlatFolder."
      },
      "description": "An entry in a serialized  {@link  FlatTree } . TODO: maybe remove the Map intermediary in the serialization process (do Folder -> object literal, instead of Folder -> Map -> object literal)"
    },
    "CardTypeBasedOnCategory<\"note\">": {
      "$ref": "#/definitions/Note",
      "description": "Helper type to get the card type associated to generic category type."
    },
    "Note": {
      "type": "object",
      "properties": {
        "_category": {
          "type": "string",
          "const": "note"
        },
        "id": {
          "$ref": "#/definitions/ID"
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ID"
          }
        },
        "title": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        }
      },
      "required": [
        "_category",
        "desc",
        "id",
        "tags",
        "title"
      ],
      "additionalProperties": false
    },
    "MetaData": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string",
          "const": "save-v3"
        },
        "lastUpdate": {
          "type": "string"
        }
      },
      "required": [
        "version",
        "lastUpdate"
      ],
      "additionalProperties": false
    }
  }
}

=== const39/lore-tracker/tests/saves/test_save_v3.json
{"name":"The Story of Aasathra ","days":13,"season":"summer","cards":{"quest":{"549c9ba859d262b305cd45c6ecc2f843":{"metadata":{"id":1687022080162,"_category":"quest","color":"#ffffff","name":"quest-root","tags":[]},"files":[{"_category":"quest","id":1624110885373,"tags":[],"title":"Le roi et Zyrlat ont disparu.","tasks":[{"desc":"Trouver des indices","isCompleted":true},{"desc":"Trouver le dragon","isCompleted":false}],"desc":"Ceci est une description de **test** d'une quête. Cette quête est la quête principale très longue."},{"_category":"quest","id":1624110853525,"tags":[],"title":"J'attends la réponse de mon oncle et le reste de la guilde des Tailleurs de Gemmes et Joailliers à ma lettre.","tasks":[],"desc":""}],"subfolders":[]}},"event":{"dcc7c2f8f999c30b87e02ae608859ffa":{"metadata":{"id":1687022080167,"_category":"event","color":"#ffffff","name":"event-root","tags":[]},"files":[{"_category":"event","id":1624116213548,"desc":"Acménos finds a hidden chest containing 20 gold coins","type":"discovery","day":6,"tags":[1624111007397]},{"_category":"event","id":1624116190216,"desc":"Travel from Langdale to Black Crystal in 3 days and a half","type":"travel","day":4,"tags":[1624110921146,1624111007397]},{"_category":"event","id":1624116066394,"desc":"We avoid an ambush thanks to the Langdale guard, lead by Captain Eivor.","type":"encounter","day":2,"tags":[1624110921146]},{"_category":"event","id":1624116032605,"desc":"We meet a bunch of hostile Kobolds in a cave. We manage to escape by winning a card game against them.","type":"encounter","day":0,"tags":[]},{"_category":"event","id":1624115974100,"desc":"Fight undeads in Hillwater suburbs","type":"combat","day":0,"tags":[1624111280816]},{"_category":"event","id":1624115562337,"desc":"Fight against pirates in Hillwater's tavern after they insulted Acménos. We then steal their ship.\n\nWe find :\n* 5 bottles of rhum\n* 100 gold coins\n* a treasure map","type":"combat","day":0,"tags":[1624111280816]}],"subfolders":[]}},"location":{"6851effa39fb742e4a557ff9dd4f06bf":{"metadata":{"id":1687022080171,"_category":"location","color":"#ffffff","name":"location-root","tags":[]},"files":[{"_category":"location","id":1624111156384,"name":"Wicked Wood","desc":"- Sur la route entre Black Crystal et Gunnolsfell\n- A l'entrée du bois : un panneau. L'indication originale \"Midwood\" est barrée et indique maintenant \"Wicked Wood\". Un conseil est écrit dessous : \"Surtout ne quittez pas le sentier.\" \n- Forêt très sombre, la canopée bloque une bonne partie de la lumière. Le sentier est dallé et comporte de nombreux virages. L'air est lourd et étouffant. Le sentier a disparu quand nous avons voulu faire demi-tour.\n- Le sentier est coupé par une rivière de 7-8m de large et plus profonde que notre hauteur. Saladdin a plongé dedans et est ressorti paralysé. Un pont délabré enjambe la rivière.\n- Des araignées géantes et leur toile, vibrante lorsque endommagée, peuplent la forêt. ","tags":[]},{"_category":"location","id":1624110921146,"name":"Langdale","desc":"**Qui est le nouveau maire ?**\n- Auberge de la Bonne Saison : consommation à moitié prix (4PC) grâce au Capitaine Eivor\n- Boutique\n- Guérisseur\n- Librairie","tags":[]},{"_category":"location","id":1624111007397,"name":"Black Crystal","desc":"**Capitale du royaume**\n- Roi exilé : Lothar Ier. \n- Le palais royal est entouré de murailles.\nBatiments : auberge du Cerf Courant, armurerie, animalerie, écurie (tenancière agressée par Salomon).\n\nLa plaine autour de Black Crystal semble avoir été un vieux champ de bataille autrefois. Cette bataille a opposé il y a 200 ans environ les peuples libres (de toutes les races) aidés d'Aspects draconiques (une race oubliée, ancêtres des dragons) bleus, blancs et verts contre les Aspects draconiques Noir et Rouge, aveuglés par leurs pouvoirs reçus des Dieux. Les peuples libres en sont sortis victorieux. Pour punir les Aspects draconiques, les dieux leur ont retiré leurs pouvoirs et leur droit d'enfanter. Tous ont décidé de ne plus s'immiscer dans la vie du monde.\nLa ville est entourée d'une muraille en pierre. Elle est immense et ancienne. Les portes en bois sont doublées d'une herse.\n\n**Durant le règne d'Aasathra :** \n* Les gardes sont très sévères et arrêtent des \"rebelles\". Des avis de recherche sont sur les murs.\n* Les habitants sont évasifs et peureux. L'armurerie et la Guilde sont abandonnées.\n* Les troubles ont commencé quelques années auparavant. D'abord par des manifestations puis des révoltes. Puis les gens ont commencé à partir par lassitude. Des nobles, dont plusieurs siégeant au conseil, ont fui la région. La politique intérieure et sécuritaire bien plus agressive depuis que l'intendant n'est plus en fonction.\n* La tête de Holg était mise à prix sur un avis de recherche (mort ou vif), la somme est importante. Recherché pour vol, refus d'obtempérer, arnaque et rébellion. \n* Les marchands ont fui car ils sont accusés de complicité avec la rébellion. Ils ont laissé une carte, signée d'Aranthus, mon oncle. ","tags":[1624115250605]},{"_category":"location","id":1624111349200,"name":"Mine abandonnée","desc":"Entre Hillwater et Langdale. \nAbandonnée il y a 1 an ou 2 lorsque les nains ont découvert la présence de Kobolds sous terre. Un ancien autel nain trouvé. Le campement nain a été débarrassé.","tags":[]},{"_category":"location","id":1624111280816,"name":"Hillwater","desc":"Petit port de commerce.\nTaverne \"Le Soifard Insatiable\".\nLa ville était à feu et à sang quand nous l'avons quittée après que des morts-vivants ont attaqué la ville.","tags":[]},{"_category":"location","id":1624111226207,"name":"Maison du Loup-garou","desc":"- Sur la route entre Wicked Wood et Darkwell, dans une plaine vallonnée verdoyante.\n- Petite maison en bois isolée dans la plaine. Elle est sens dessus-dessous et des cadavres d'animaux sont entreposés dans le sous-sol. Le responsable est un loup-garou, d'après les bandits qui nous ont attaqués et l'avis de recherche qu'ils avaient.","tags":[]},{"_category":"location","id":1624111262104,"name":"Darkwell","desc":"* Sur la route entre Wicked Wood et Gunnolsfell\n* Repaire de bandits et brigands. Continuellement dans l'agitation générale : bagarres et autre chaos sont perpétuels.\n* Dirigée par la mafia de Black Jack ","tags":[1624115755471]}],"subfolders":[]}},"character":{"96391ee5c839bf017a0ebd87a02a018b":{"metadata":{"id":1687022260296,"_category":"character","name":"test folder","color":"#ffc107","tags":[]},"files":[],"parent":"04a9b9f59950cd609fdc7d24d568ac69","subfolders":[]},"04a9b9f59950cd609fdc7d24d568ac69":{"metadata":{"id":1687022180183,"_category":"character","name":"Explorers' Guild","color":"#F4EF03","tags":[]},"files":[{"_category":"character","id":1687022264499,"desc":"","tags":[],"name":"test b","race":"","classes":"","role":"","isAlive":true,"isNPC":true}],"parent":"09d177f233c91dbf1edb7711818a8380","subfolders":["96391ee5c839bf017a0ebd87a02a018b"]},"dca25aa9df219e5a0cc4d261b9fcb79b":{"metadata":{"id":1687022220415,"_category":"character","name":"Gnomeregan's City Council","color":"#4D36F4","tags":[1687022180183]},"files":[{"_category":"character","id":1687022250680,"desc":"","tags":[],"name":"test c","race":"","classes":"","role":"","isAlive":true,"isNPC":true},{"_category":"character","id":1687022247069,"desc":"","tags":[],"name":"test b","race":"","classes":"","role":"","isAlive":true,"isNPC":true},{"_category":"character","id":1687022243551,"desc":"","tags":[],"name":"test a","race":"","classes":"","role":"","isAlive":true,"isNPC":true}],"parent":"09d177f233c91dbf1edb7711818a8380","subfolders":[]},"09d177f233c91dbf1edb7711818a8380":{"metadata":{"id":1687022080177,"_category":"character","color":"#ffffff","name":"character-root","tags":[]},"files":[{"_category":"character","id":1624115755471,"name":"Black Jack","race":"Tiefling","classes":"","role":"Mafia leader","isNPC":true,"isAlive":true,"desc":"Tiefling in a long red coat. He controls the town of Darkwell. Owns a large manor, guarded by 2 half-orcs.","tags":[1624111262104]},{"_category":"character","id":1624115556508,"name":"Thalia","race":"Human","classes":"Monkess","role":"","isNPC":true,"isAlive":true,"desc":"Mysterious human monk met in Wicked Wood. She helps us fighting the giant spiders of the wood. She's part of a monk brotherhood and undergone a long training with them since her childhood.\nShe apparently owns large amounts of money to an unknown person.","tags":[1624111156384,1687022180183]},{"_category":"character","id":1624122871328,"name":"Saladdin","race":"Half-elf","classes":"Sorcerer","role":"","isNPC":false,"isAlive":true,"desc":"Newest member of the team. We met him in a tavern and he followed along.","tags":[1624116821392,1624122024695,1624122708679,1624115755471,1624115483395,1624122759481,1624115556508]},{"_category":"character","id":1624122759481,"name":"Salomon","race":"Drow","classes":"Cleric","role":"","isNPC":false,"isAlive":true,"desc":"Healer of the team.","tags":[1624111007397,1624122024695]},{"_category":"character","id":1624115483395,"name":"Holg","race":"Half-orc","classes":"","role":"Smuggler/Resistance member","isNPC":true,"isAlive":true,"desc":"An old friend from my smuggler days. He was Alric sidekick in the resistance. Since we parted ways 20 years ago, he simply enjoyed life around the continent before coming to Black Crystal and join the resistance. Now, he intends to lead a unit in the city garrison.","tags":[1624115396696,1624111007397,1624116821392]},{"_category":"character","id":1624115396696,"name":"Alric","race":"Humain","classes":"","role":"Warrior/Resistance leader","isNPC":true,"isAlive":true,"desc":"Halvor's old acquaintance. Was arrested by the city guards for having led an assault against the king.","tags":[1624111007397]},{"_category":"character","id":1624115439458,"name":"Lathandre","race":"Semi-god","classes":"","role":"","isNPC":true,"isAlive":true,"desc":"Semi-god worshipped by Alix","tags":[1624111863797]},{"_ca
